#%RAML 0.8

title: Test Contract

/basic:
  get:
    responses:
      200:
        description: Success
        body:
          application/json:
  post:
    body:
      application/json:
      application/xml:

/parametrized/{key}/data:
  get:
    responses:
      200:
        description: Success
  /subresource:
    get:
      responses:
        200:
          description: Success

/uri-params:
  /enum/{enum}:
    uriParameters:
      enum:
        type: string
        enum: [ FOO, BAR ]
    get:
      responses:
        200:
          description: Success
  /int/{int}:
    uriParameters:
      int:
        type: integer
    get:
      responses:
        200:
          description: Success
  /num/{num}:
    uriParameters:
      num:
        type: number
    get:
      responses:
        200:
          description: Success
  /bool/{bool}:
    uriParameters:
      bool:
        type: boolean
    get:
      responses:
        200:
          description: Success

/query-params:
  get:
    queryParameters:
      status:
        type: string
        enum: [ FOO, BAR ]
        required: false
      version:
        type: integer
        required: true
    responses:
      200:
        description: Success

/headers:
  get:
    headers:
      Some-Header:
        type: string
        enum: [ FOO, BAR ]
        required: true
      Int-Header:
        type: integer
        required: false
      Num-Header:
        type: number
        required: false
      Bool-Header:
        type: boolean
        required: false
      Regex-Header-{?}:
        type: integer
        required: false
    responses:
      200:
        description: Success

/response:
  head:
    responses:
      200:
        description: Success
  get:
    responses:
      200:
        description: Success
        body:
          application/json:

  /wrong-content-type:
    get:
      responses:
        200:
          description: Success
          body:
            application/json: